### ISSUE TITLE
Why do you call it "Git"?

### ISSUE THREAD

**Issue by amirhfarzaneh** [kjanjua26/Git-Loss-For-Deep-Face-Recognition#4]
Hello,

Great job on implementation and the paper. Why do you call it "Git" is it short for something in particular?

**Comment by kjanjua26** [comment]
Hi, we just took the name inspiration from Git version control. We did write a small explanation in the paper itself. Here: 

**_The name of the loss function is inspired by two common Git version control software commands, "push" and "pull", which are semantically similar to the aim of this work: push away features of different identities while pulling together features belonging to the same identity._**

Please close the issue if you are question has been answered.

**Comment by amirhfarzaneh** [comment]
Oh that makes sense. Thank you for then clarification :-)

**Comment by kjanjua26** [comment]
No problem. I am closing the issue now. Feel free to re-open if you need anything else.
